name: Release

on:
  push:
    tags:
      #- 'v*'
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            asset_name: openapi_cli_linux
          - target: x86_64-apple-darwin
            asset_name: openapi_cli_macos
          - target: x86_64-pc-windows-gnu
            asset_name: openapi_cli_windows.exe

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Install Cross
        run: cargo install cross
      - name: Build
        run: cross build --release --target ${{ matrix.target }} --verbose
      - name: Rename
        run: mv target/${{ matrix.target }}/release/openapi_cli target/${{ matrix.target }}/release/${{ matrix.asset_name }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: target/${{ matrix.target }}/release/${{ matrix.asset_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: .
      - name: Upload Release Asset (Linux)
        id: upload_release_asset_linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openapi_cli_linux
          asset_name: openapi_cli_linux
          asset_content_type: application/octet-stream
      - name: Upload Release Asset (macOS)
        id: upload_release_asset_macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openapi_cli_macos
          asset_name: openapi_cli_macos
          asset_content_type: application/octet-stream
      - name: Upload Release Asset (Windows)
        id: upload_release_asset_windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openapi_cli_windows.exe
          asset_name: openapi_cli_windows.exe
          asset_content_type: application/octet-stream
